const express = require('express');
const { randomUUID } = require('crypto');
const multer = require('multer');
const path = require('path');
const { getMonitoringSnapshot } = require('../models/monitoring');

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (req, file, callback) => {
    const allowedExtensions = ['.pdf', '.doc', '.docx', '.dwg', '.dxf', '.png', '.jpg', '.jpeg'];
    const extension = path.extname(file.originalname).toLowerCase();
    callback(null, allowedExtensions.includes(extension));
  },
});

const choices = {
  country: ['SG', 'MY'],
  property: ['Landed', 'Condo', 'C&I'],
  roof: ['Tile Roof', 'RC Roof', 'Mix', "I don't know"],
  steepness: ['Standard Roof', 'Steep Roof', "I don't know"],
  storeys: ['1', '2', '3', 'Other'],
  meter: ['63A 1-Phase', '63A 3-Phase', '100A 1-Phase', '100A 3-Phase', '200A and above', "I don't know"],
};

const DEFAULT_PANEL_COUNT = 30;
const PANEL_AREA_SQUARE_METERS = 2.6;
const USABLE_ROOF_RATIO = 0.75;
const MAX_PANEL_COUNT = 10000;
const LEAD_NURTURE_NOTE = 'Lead declined for installation — enrolled into automated marketing sequence (monthly solar educational brochures, tariff hike updates, and promotional flyers).';

function roofAreaSquareMeters(points) {
  const earthRadiusMeters = 6378137;
  const radiansPerDegree = Math.PI / 180;
  let areaSum = 0;

  points.forEach((point, index) => {
    const nextPoint = points[(index + 1) % points.length];
    const latitude = point.lat * radiansPerDegree;
    const nextLatitude = nextPoint.lat * radiansPerDegree;
    let longitudeDelta = (nextPoint.lng - point.lng) * radiansPerDegree;

    if (longitudeDelta > Math.PI) longitudeDelta -= 2 * Math.PI;
    if (longitudeDelta < -Math.PI) longitudeDelta += 2 * Math.PI;

    areaSum += longitudeDelta * (2 + Math.sin(latitude) + Math.sin(nextLatitude));
  });

  return Math.abs(areaSum) * earthRadiusMeters ** 2 / 2;
}

function panelCountForRoof(points) {
  if (points.length < 3) return DEFAULT_PANEL_COUNT;

  const usableArea = roofAreaSquareMeters(points) * USABLE_ROOF_RATIO;
  return Math.min(MAX_PANEL_COUNT, Math.max(1, Math.floor(usableArea / PANEL_AREA_SQUARE_METERS)));
}

function createMockPdf(title, details) {
  const cleanText = (value) => String(value).replace(/[^\x20-\x7e]/g, '?').replace(/[\\()]/g, '\\$&');
  const lines = [title, ...details].slice(0, 18);
  const textStream = [
    'BT',
    '/F1 18 Tf',
    '54 744 Td',
    `(${cleanText(lines[0])}) Tj`,
    '/F1 11 Tf',
    ...lines.slice(1).flatMap((line) => ['0 -24 Td', `(${cleanText(line)}) Tj`]),
    'ET',
  ].join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(textStream, 'ascii')} >>\nstream\n${textStream}\nendstream`,
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, 'ascii'));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'ascii');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => { pdf += `${String(offset).padStart(10, '0')} 00000 n \n`; });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'ascii');
}

function documentFile(key, title, stageTag, file) {
  if (!file) return { key, title, stageTag, available: false };
  const size = file.buffer.length;
  return {
    key,
    title,
    stageTag,
    available: true,
    filename: file.filename,
    contentType: file.contentType,
    buffer: file.buffer,
    fileType: file.contentType === 'application/pdf' ? 'PDF' : path.extname(file.filename).slice(1).toUpperCase() || 'FILE',
    fileSize: size >= 1024 * 1024 ? `${(size / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(size / 1024))} KB`,
  };
}

function projectDocuments(project) {
  const currency = project.estimate.currency;
  const money = new Intl.NumberFormat(currency === 'SGD' ? 'en-SG' : 'en-MY', { style: 'currency', currency, maximumFractionDigits: 2 });
  const quotation = project.proposal || {
    filename: `${project.id}-quotation-proposal.pdf`,
    contentType: 'application/pdf',
    buffer: createMockPdf('Solar Quotation & Proposal', [
      `Project: ${project.id}`,
      `Client: ${project.customerName}`,
      `Property: ${project.propertyDisplay || project.property}`,
      `System: ${project.estimate.capacityKwp.toFixed(2)} kWp`,
      `Contract estimate: ${money.format(project.estimate.totalCost)}`,
      'Demo copy generated by the Gainmax prototype.',
    ]),
  };
  const milestones = project.paymentMilestones || [
    { percentage: 20, amount: project.estimate.totalCost * 0.2, label: 'Project confirmation' },
    { percentage: 30, amount: project.estimate.totalCost * 0.3, label: 'Before installation' },
    { percentage: 50, amount: project.estimate.totalCost * 0.5, label: 'Project handover' },
  ];
  const receiptKeys = ['deposit', 'preinstall', 'handover'];
  const invoiceTitles = ['20% Deposit Invoice', '30% Pre-install Invoice', '50% Handover Invoice'];
  const invoices = milestones.map((milestone, index) => {
    const key = `invoice-${receiptKeys[index]}`;
    const invoiceFile = {
      filename: `${project.id}-${receiptKeys[index]}-invoice.pdf`,
      contentType: 'application/pdf',
      buffer: createMockPdf(invoiceTitles[index], [
        `Project: ${project.id}`,
        `Client: ${project.customerName}`,
        `Milestone: ${milestone.percentage}% - ${milestone.label}`,
        `Amount due: ${money.format(milestone.amount)}`,
        'Demo invoice generated by the Gainmax prototype.',
      ]),
    };
    return {
      invoice: documentFile(key, invoiceTitles[index], `Finance · ${milestone.percentage}%`, invoiceFile),
      receipt: documentFile(`receipt-${receiptKeys[index]}`, `${milestone.percentage}% Payment Receipt`, 'Client upload', project.receipts?.[receiptKeys[index]]),
      receiptKey: receiptKeys[index],
    };
  });
  const skom = project.skomSigned ? {
    filename: `${project.id}-signed-skom.pdf`,
    contentType: 'application/pdf',
    buffer: createMockPdf('Signed SKOM - Agree to Proceed', [
      `Project: ${project.id}`,
      `Client: ${project.customerName}`,
      `Signed: ${project.skomSignedAt ? new Date(project.skomSignedAt).toLocaleString('en-SG') : 'Confirmed'}`,
      'The client signed the Agree to Proceed authorization.',
      'The original signature image is held with the project record.',
    ]),
  } : null;
  const acceptance = project.engineering.acceptanceComplete ? {
    filename: `${project.id}-final-acceptance-certificate.pdf`,
    contentType: 'application/pdf',
    buffer: createMockPdf('Final Acceptance Certificate', [
      `Project: ${project.id}`,
      `Client: ${project.customerName}`,
      `Accepted by: ${project.engineering.acceptanceBy || 'Project team'}`,
      `Recorded: ${project.engineering.acceptanceAt ? new Date(project.engineering.acceptanceAt).toLocaleDateString('en-SG') : 'Completed'}`,
      project.engineering.acceptanceNotes || 'Final acceptance checklist completed.',
    ]),
  } : null;

  return [
    {
      title: 'Contracts & Finance',
      documents: [
        documentFile('proposal', 'Initial Quotation & Proposal', 'Sales quote', quotation),
        ...invoices.flatMap(({ invoice, receipt }) => [invoice, receipt]),
      ],
    },
    {
      title: 'Engineering & Execution',
      documents: [
        documentFile('drawing', 'Approved Layout / Single-Line Drawing', 'Stage 2 · Finalise drawing', project.engineering.drawing),
        documentFile('timeline', 'Project Master Timeline', 'Stage 7 · Timeline finalised', project.engineering.timeline),
        documentFile('skom', 'Signed SKOM · Agree to Proceed', 'Stage 6 · SKOM', skom),
      ],
    },
    {
      title: 'Handover & Warranty',
      documents: [
        documentFile('acceptance', 'Final Acceptance Certificate', 'Stage 10 · Handover', acceptance),
        documentFile('warranty', 'Solar Panel & Inverter Product Warranty Sheets', 'Stage 10 · Handover', project.engineering.warranty),
      ],
    },
  ];
}

function estimateFor(input) {
  const rateByProperty = { Landed: 1.4, Condo: 1.6, 'C&I': 1.2 };
  const currency = input.country === 'SG' ? 'SGD' : 'MYR';
  const capacityKwp = (Number(input.panels) * 640) / 1000;
  const basePrice = capacityKwp * 1000 * rateByProperty[input.property];
  const systemPrice = basePrice * (input.steepness === 'Steep Roof' ? 1.1 : 1);
  const gst = input.country === 'SG' ? systemPrice * 0.09 : 0;
  const monthlyYield = (capacityKwp * 3.4 * 365) / 12;

  return {
    currency,
    capacityKwp,
    basePrice: Math.round(systemPrice * 100) / 100,
    gst: Math.round(gst * 100) / 100,
    totalCost: Math.round((systemPrice + gst) * 100) / 100,
    monthlyYield: Math.round(monthlyYield),
    monthlySavings: Math.round(monthlyYield * 0.21 * 100) / 100,
  };
}

function quoteDetailsFrom(body) {
  const { country, property, roof, steepness, storeys, meter } = body;
  const customerName = (body.customerName || '').trim();
  const customerPhone = (body.customerPhone || '').trim();
  const customerEmail = (body.customerEmail || '').trim();
  const companyName = (body.companyName || '').trim();
  const monthlyBill = body.billUnknown === 'true' || body.monthlyBill === ''
    ? null
    : Number(body.monthlyBill);
  const postalCode = (body.postalCode || '').trim();
  let roofOutline = [];

  try {
    roofOutline = body.roofOutline ? JSON.parse(body.roofOutline) : [];
  } catch (error) {
    return null;
  }

  if (
    !choices.country.includes(country) ||
    !choices.property.includes(property) ||
    !choices.roof.includes(roof) ||
    !choices.steepness.includes(steepness) ||
    !choices.storeys.includes(storeys) ||
    !choices.meter.includes(meter) ||
    !customerName || customerName.length > 100 ||
    !/^[0-9+() -]{7,20}$/.test(customerPhone) ||
    customerEmail.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(customerEmail) ||
    companyName.length > 100 ||
    postalCode.length > 20 ||
    !Array.isArray(roofOutline) ||
    roofOutline.length > 100 ||
    roofOutline.some((point) =>
      !point ||
      !Number.isFinite(point.lat) ||
      !Number.isFinite(point.lng) ||
      point.lat < -90 || point.lat > 90 ||
      point.lng < -180 || point.lng > 180
    ) ||
    (monthlyBill !== null && (!Number.isFinite(monthlyBill) || monthlyBill < 0))
  ) {
    return null;
  }

  const panels = panelCountForRoof(roofOutline);
  const roofArea = roofOutline.length >= 3
    ? Math.round(roofAreaSquareMeters(roofOutline) * 10) / 10
    : null;

  return { country, property, roof, steepness, storeys, meter, panels, monthlyBill, customerName, customerPhone, customerEmail, companyName, postalCode, roofOutline, roofArea };
}

module.exports = (leads, mapsApiKey = '') => {
  const router = express.Router();
  const pendingEstimates = new Map();

  function removeExpiredEstimates() {
    const now = Date.now();
    for (const [token, draft] of pendingEstimates) {
      if (draft.expiresAt <= now) pendingEstimates.delete(token);
    }
  }

  router.get('/', (req, res) => res.redirect('/customer'));
  router.get('/customer', (req, res) => res.render('quote', { mapsApiKey }));
  router.get('/client/project', (req, res) => {
    const activeProjects = leads.filter((lead) => lead.status === 'Sales Closed')
      .sort((first, second) => second.salesClosedAt - first.salesClosedAt);
    const project = activeProjects.find((lead) => lead.id === req.query.projectId) || activeProjects[0] || null;
    res.render('client-dashboard', {
      project,
      documentGroups: project ? projectDocuments(project) : [],
      monitoring: project ? getMonitoringSnapshot(project) : null,
      activeTab: ['project', 'documents', 'monitoring', 'referrals', 'feedback'].includes(req.query.tab) ? req.query.tab : 'project',
      receiptUploaded: req.query.receiptUploaded === '1',
      currentRole: req.cookies?.demoRole || null,
    });
  });

  router.get('/client/projects/:id/documents/:documentKey', (req, res) => {
    const project = leads.find((lead) => lead.id === req.params.id && lead.status === 'Sales Closed');
    if (!project) return res.sendStatus(404);
    const document = projectDocuments(project)
      .flatMap((group) => group.documents)
      .find((item) => item.key === req.params.documentKey && item.available);
    if (!document) return res.sendStatus(404);
    res.set('Cache-Control', 'no-store');
    res.type(document.contentType || 'application/octet-stream');
    res.attachment(document.filename);
    res.send(document.buffer);
  });

  router.post('/client/projects/:id/receipts/:milestone', upload.single('receipt'), (req, res) => {
    const project = leads.find((lead) => lead.id === req.params.id && lead.status === 'Sales Closed');
    const validMilestones = ['deposit', 'preinstall', 'handover'];
    if (!project || !validMilestones.includes(req.params.milestone)) return res.sendStatus(404);
    if (!req.file) return res.status(400).send('Choose a PDF or image receipt to upload.');
    project.receipts ||= {};
    project.receipts[req.params.milestone] = {
      filename: req.file.originalname,
      contentType: req.file.mimetype,
      buffer: req.file.buffer,
      uploadedAt: new Date(),
    };
    res.redirect(`/client/project?projectId=${encodeURIComponent(project.id)}&tab=documents&receiptUploaded=1`);
  });

  router.get('/engineer/om', (req, res) => {
    const projects = leads.filter((lead) => lead.status === 'Sales Closed')
      .map((project) => ({ project, monitoring: getMonitoringSnapshot(project) }));
    res.render('om-center', { projects });
  });

  router.post('/engineer/om/projects/:projectId/alarms/:alarmId/resolve', (req, res) => {
    const project = leads.find((lead) => lead.id === req.params.projectId && lead.status === 'Sales Closed');
    if (!project) return res.sendStatus(404);
    project.monitoring ||= getMonitoringSnapshot(project);
    const alarmIndex = project.monitoring.activeAlarms.findIndex((alarm) => alarm.id === req.params.alarmId);
    if (alarmIndex < 0) return res.sendStatus(404);
    const [alarm] = project.monitoring.activeAlarms.splice(alarmIndex, 1);
    project.monitoring.resolvedAlarms.unshift({ ...alarm, severity: 'Normal', detail: `${alarm.detail} Resolved by Engineering.`, since: `Resolved ${new Date().toLocaleDateString('en-SG')}` });
    res.redirect('/engineer/om');
  });

  router.post('/client/projects/:id/skom', (req, res) => {
    const project = leads.find((lead) => lead.id === req.params.id && lead.status === 'Sales Closed');
    const signatureData = String(req.body.signatureData || '');
    if (signatureData.length > 60 * 1024) return res.sendStatus(413);
    const signatureMatch = /^data:image\/png;base64,([A-Za-z0-9+/]+={0,2})$/.exec(signatureData);
    if (!project || (project.currentStage || 1) !== 6 || project.skomSigned || !signatureMatch) return res.sendStatus(400);

    const signature = Buffer.from(signatureMatch[1], 'base64');
    const pngSignature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
    if (
      signature.length < pngSignature.length ||
      signature.length > 45 * 1024 ||
      !signature.subarray(0, pngSignature.length).equals(pngSignature)
    ) {
      return res.sendStatus(400);
    }

    project.skomSigned = true;
    project.skomSignedAt = new Date();
    project.skomSignature = signature;
    res.sendStatus(204);
  });

  router.post('/solar-snapshot', (req, res) => {
    const details = quoteDetailsFrom(req.body);
    if (!details) return res.status(400).send('Please provide valid quotation and contact details.');

    removeExpiredEstimates();
    const token = randomUUID();
    pendingEstimates.set(token, {
      details,
      estimate: estimateFor(details),
      expiresAt: Date.now() + 30 * 60 * 1000,
    });

    res.redirect(303, `/solar-snapshot/${token}`);
  });

  router.get('/solar-snapshot/:token', (req, res) => {
    removeExpiredEstimates();
    const draft = pendingEstimates.get(req.params.token);
    if (!draft) return res.status(404).send('This estimate has expired. Please start a new quote.');

    const annualSavings = draft.estimate.monthlySavings * 12;
    const degradedLifetimeFactor = Array.from({ length: 25 }, (_, year) => 0.995 ** year)
      .reduce((total, yearFactor) => total + yearFactor, 0);
    const annualGenerationKwh = draft.estimate.monthlyYield * 12;
    const annualCo2Tonnes = (annualGenerationKwh * 0.4) / 1000;

    res.render('solar-snapshot', {
      draft,
      token: req.params.token,
      annualSavings,
      lifetimeSavingsLow: annualSavings * degradedLifetimeFactor,
      lifetimeSavingsHigh: annualSavings * 25,
      annualGenerationMwh: annualGenerationKwh / 1000,
      annualCo2Tonnes,
      carEquivalent: annualCo2Tonnes / 4.6,
      treeEquivalent: (annualCo2Tonnes * 1000) / 21.77,
    });
  });

  router.post('/submit-lead', (req, res) => {
    removeExpiredEstimates();
    const draft = pendingEstimates.get(req.body.estimateToken);
    if (!draft) return res.status(400).send('This estimate has expired. Please request a new estimate.');

    leads.unshift({
      id: randomUUID(),
      createdAt: new Date(),
      status: 'Pending Review',
      skomSigned: false,
      ...draft.details,
      estimate: draft.estimate,
    });
    pendingEstimates.delete(req.body.estimateToken);

    res.redirect('/sales/leads');
  });

  router.get('/sales/leads', (req, res) => res.render('sales-leads', { leads }));
  router.get('/sales-leads', (req, res) => res.redirect('/sales/leads'));

  router.post('/sales/leads/:id/decline', (req, res) => {
    const lead = leads.find((entry) => entry.id === req.params.id);
    if (!lead || !['Pending', 'Pending Review'].includes(lead.status)) return res.sendStatus(404);
    const enrolledAt = new Date();
    lead.status = 'Brochure Campaign (Nurtured)';
    lead.declinedAt = enrolledAt;
    lead.declineNote = LEAD_NURTURE_NOTE;
    lead.marketingCampaign = {
      status: 'Enrolled',
      cadence: 'Monthly',
      enrolledAt,
      nextTouchAt: new Date(enrolledAt.getTime() + 30 * 24 * 60 * 60 * 1000),
      sequence: ['Solar educational brochures', 'Tariff hike updates', 'Promotional flyers'],
    };
    res.redirect('/sales/leads');
  });

  router.post('/sales/leads/:id/handoff', upload.single('proposal'), (req, res) => {
    const lead = leads.find((entry) => entry.id === req.params.id);
    const percentages = [req.body.confirmationPercent, req.body.installationPercent, req.body.handoverPercent].map(Number);
    if (!lead || !['Pending', 'Pending Review'].includes(lead.status)) return res.sendStatus(404);
    if (!req.file) return res.status(400).send('Upload the customer proposal before handing over this project.');
    if (
      percentages.some((percentage) => !Number.isFinite(percentage) || percentage <= 0 || percentage > 100) ||
      Math.abs(percentages.reduce((total, percentage) => total + percentage, 0) - 100) > 0.01
    ) {
      return res.status(400).send('Payment milestone percentages must total 100%.');
    }

    const labels = ['Project confirmation', 'Before installation', 'Project handover'];
    lead.status = 'Sales Closed';
    lead.salesClosedAt = new Date();
    lead.proposal = {
      filename: req.file.originalname,
      contentType: req.file.mimetype,
      buffer: req.file.buffer,
    };
    lead.specialCustomerRequests = String(req.body.specialCustomerRequests || '').trim().slice(0, 4000);
    lead.paymentMilestones = percentages.map((percentage, index) => ({
      label: labels[index],
      percentage,
      amount: Math.round(lead.estimate.totalCost * percentage) / 100,
    }));
    lead.engineering = {
      assignedEngineer: '',
      siteSupervisor: '',
      drawingPreparedBy: '',
      drawing: null,
      bom: { panels: false, inverters: false, racking: false },
      shipping: {
        mounting: { status: 'Not dispatched', arrived: false },
        panels: { status: 'Not dispatched', arrived: false },
      },
      timeline: null,
      toolboxWorkers: '',
      wipStatus: 'Not started',
      acceptanceBy: '',
      acceptanceNotes: '',
      acceptanceComplete: false,
      warranty: null,
    };
    lead.currentStage = 1;
    lead.completedAt = null;
    res.redirect('/engineer/review');
  });

  router.get('/engineer/review', (req, res) => {
    const projects = leads.filter((lead) => lead.status === 'Sales Closed')
      .sort((first, second) => second.salesClosedAt - first.salesClosedAt);
    const selectedProject = projects.find((project) => project.id === req.query.projectId) || projects[0] || null;
    res.render('engineer-review', { projects, selectedProject, notice: req.query.notice || '' });
  });

  router.get('/engineer/projects/:id/proposal', (req, res) => {
    const project = leads.find((lead) => lead.id === req.params.id && lead.status === 'Sales Closed');
    if (!project?.proposal) return res.sendStatus(404);
    res.type(project.proposal.contentType || 'application/octet-stream');
    res.attachment(project.proposal.filename);
    res.send(project.proposal.buffer);
  });

  router.post('/engineer/projects/:id/update-stage', upload.fields([
    { name: 'drawing', maxCount: 1 },
    { name: 'timeline', maxCount: 1 },
    { name: 'warranty', maxCount: 1 },
  ]), (req, res) => {
    const project = leads.find((lead) => lead.id === req.params.id && lead.status === 'Sales Closed');
    if (!project) return res.sendStatus(404);
    const projectId = encodeURIComponent(project.id);
    const engineering = project.engineering;
    const files = req.files || {};
    const storeFile = (file) => ({ filename: file.originalname, contentType: file.mimetype, buffer: file.buffer, uploadedAt: new Date() });
    const redirectWithNotice = (notice) => res.redirect(`/engineer/review?projectId=${projectId}&notice=${encodeURIComponent(notice)}`);
    const action = req.body.action;
    if (project.completedAt) return redirectWithNotice('This project is already complete.');

    if (action === 'save-assignment') {
      engineering.assignedEngineer = String(req.body.assignedEngineer || '').trim().slice(0, 100);
      engineering.siteSupervisor = String(req.body.siteSupervisor || '').trim().slice(0, 100);
      return redirectWithNotice('Project team saved.');
    }
    if (action === 'save-drawing') {
      engineering.drawingPreparedBy = String(req.body.preparedBy || '').trim().slice(0, 100);
      if (files.drawing?.[0]) engineering.drawing = storeFile(files.drawing[0]);
      if (!engineering.drawingPreparedBy || !engineering.drawing) return redirectWithNotice('Add a preparer name and upload the engineering drawing.');
      return redirectWithNotice('Engineering drawing saved.');
    }
    if (action === 'save-bom') {
      engineering.bom = { panels: req.body.panels === 'on', inverters: req.body.inverters === 'on', racking: req.body.racking === 'on' };
      return redirectWithNotice('BOM checklist saved.');
    }
    if (action === 'save-shipping') {
      const statuses = ['Not dispatched', 'Dispatched', 'In transit'];
      const mountingStatus = statuses.includes(req.body.mountingStatus) ? req.body.mountingStatus : 'Not dispatched';
      const panelsStatus = statuses.includes(req.body.panelsStatus) ? req.body.panelsStatus : 'Not dispatched';
      engineering.shipping = {
        mounting: { status: mountingStatus, arrived: req.body.mountingArrived === 'on' },
        panels: { status: panelsStatus, arrived: req.body.panelsArrived === 'on' },
      };
      return redirectWithNotice('Shipping status saved.');
    }
    if (action === 'save-timeline') {
      if (files.timeline?.[0]) engineering.timeline = storeFile(files.timeline[0]);
      return redirectWithNotice(engineering.timeline ? 'Project timeline saved.' : 'Upload the finalized project timeline.');
    }
    if (action === 'save-toolbox') {
      engineering.toolboxWorkers = String(req.body.toolboxWorkers || '').trim().slice(0, 4000);
      return redirectWithNotice(engineering.toolboxWorkers ? 'Toolbox meeting worker list saved.' : 'Add the toolbox meeting worker list.');
    }
    if (action === 'save-wip') {
      const statuses = ['Not started', 'In progress', 'On hold', 'Work complete'];
      engineering.wipStatus = statuses.includes(req.body.wipStatus) ? req.body.wipStatus : 'Not started';
      engineering.wipNotes = String(req.body.wipNotes || '').trim().slice(0, 2000);
      return redirectWithNotice('Work-in-progress status saved.');
    }
    if (action === 'save-acceptance') {
      engineering.acceptanceBy = String(req.body.acceptanceBy || '').trim().slice(0, 100);
      engineering.acceptanceNotes = String(req.body.acceptanceNotes || '').trim().slice(0, 2000);
      engineering.acceptanceComplete = req.body.acceptanceComplete === 'on';
      engineering.acceptanceAt = engineering.acceptanceComplete ? new Date() : null;
      if (files.warranty?.[0]) engineering.warranty = storeFile(files.warranty[0]);
      return redirectWithNotice('Final acceptance details saved.');
    }
    if (action !== 'advance') return res.sendStatus(400);

    const currentStage = Number(project.currentStage) || 1;
    const advanceChecks = [
      () => engineering.assignedEngineer && engineering.siteSupervisor,
      () => engineering.drawing && engineering.drawingPreparedBy,
      () => engineering.bom.panels && engineering.bom.inverters && engineering.bom.racking,
      () => ['Dispatched', 'In transit'].includes(engineering.shipping.mounting.status) && ['Dispatched', 'In transit'].includes(engineering.shipping.panels.status),
      () => engineering.shipping.mounting.arrived && engineering.shipping.panels.arrived,
      () => project.skomSigned,
      () => engineering.timeline,
      () => engineering.toolboxWorkers,
      () => engineering.wipStatus === 'Work complete',
      () => engineering.acceptanceComplete && engineering.acceptanceBy && engineering.warranty,
    ];
    const readinessMessages = [
      'Assign a site engineer and site supervisor before advancing.',
      'Upload the engineering drawing and add the preparer before advancing.',
      'Confirm panels, inverters, and racking in the BOM before advancing.',
      'Record dispatch status for both mounting structure and solar panels before advancing.',
      'Confirm arrival of both mounting structure and solar panels before advancing.',
      'The project cannot advance until the client signs SKOM.',
      'Upload the finalized project timeline before advancing.',
      'Save the toolbox meeting worker list before advancing.',
      'Set WIP status to Work complete before advancing.',
      'Complete final acceptance and upload the product warranty before closing the project.',
    ];
    if (currentStage < 1 || currentStage > 10 || !advanceChecks[currentStage - 1]()) {
      return redirectWithNotice(readinessMessages[Math.max(0, Math.min(9, currentStage - 1))]);
    }
    if (currentStage === 10) {
      project.completedAt = new Date();
    } else {
      project.currentStage = currentStage + 1;
    }
    project.stageUpdatedAt = new Date();
    redirectWithNotice(currentStage === 10 ? 'Project marked complete.' : `Project advanced to Stage ${currentStage + 1}.`);
  });

  router.get('/engineer/projects/:id/:document', (req, res, next) => {
    if (!['drawing', 'timeline', 'warranty'].includes(req.params.document)) return next();
    const project = leads.find((lead) => lead.id === req.params.id && lead.status === 'Sales Closed');
    const document = project?.engineering?.[req.params.document];
    if (!document) return res.sendStatus(404);
    res.type(document.contentType || 'application/octet-stream');
    res.attachment(document.filename);
    res.send(document.buffer);
  });

  return router;
};